// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.1
// source: classify.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClassifyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Text content to classify.
	Text          string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassifyRequest) Reset() {
	*x = ClassifyRequest{}
	mi := &file_classify_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyRequest) ProtoMessage() {}

func (x *ClassifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_classify_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyRequest.ProtoReflect.Descriptor instead.
func (*ClassifyRequest) Descriptor() ([]byte, []int) {
	return file_classify_proto_rawDescGZIP(), []int{0}
}

func (x *ClassifyRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ClassifyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the text is considered safe.
	Safe bool `protobuf:"varint,1,opt,name=safe,proto3" json:"safe,omitempty"`
	// Injection probability score (0.0 = safe, 1.0 = injection).
	Score float32 `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	// Classification label (e.g., "SAFE", "INJECTION").
	Label         string `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassifyResponse) Reset() {
	*x = ClassifyResponse{}
	mi := &file_classify_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyResponse) ProtoMessage() {}

func (x *ClassifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_classify_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyResponse.ProtoReflect.Descriptor instead.
func (*ClassifyResponse) Descriptor() ([]byte, []int) {
	return file_classify_proto_rawDescGZIP(), []int{1}
}

func (x *ClassifyResponse) GetSafe() bool {
	if x != nil {
		return x.Safe
	}
	return false
}

func (x *ClassifyResponse) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ClassifyResponse) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

var File_classify_proto protoreflect.FileDescriptor

const file_classify_proto_rawDesc = "" +
	"\n" +
	"\x0eclassify.proto\x12\x11argus.classify.v1\"%\n" +
	"\x0fClassifyRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"R\n" +
	"\x10ClassifyResponse\x12\x12\n" +
	"\x04safe\x18\x01 \x01(\bR\x04safe\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label2j\n" +
	"\x0fClassifyService\x12W\n" +
	"\fClassifyText\x12\".argus.classify.v1.ClassifyRequest\x1a#.argus.classify.v1.ClassifyResponseB'Z%github.com/zoobz-io/argus/proto;protob\x06proto3"

var (
	file_classify_proto_rawDescOnce sync.Once
	file_classify_proto_rawDescData []byte
)

func file_classify_proto_rawDescGZIP() []byte {
	file_classify_proto_rawDescOnce.Do(func() {
		file_classify_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_classify_proto_rawDesc), len(file_classify_proto_rawDesc)))
	})
	return file_classify_proto_rawDescData
}

var file_classify_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_classify_proto_goTypes = []any{
	(*ClassifyRequest)(nil),  // 0: argus.classify.v1.ClassifyRequest
	(*ClassifyResponse)(nil), // 1: argus.classify.v1.ClassifyResponse
}
var file_classify_proto_depIdxs = []int32{
	0, // 0: argus.classify.v1.ClassifyService.ClassifyText:input_type -> argus.classify.v1.ClassifyRequest
	1, // 1: argus.classify.v1.ClassifyService.ClassifyText:output_type -> argus.classify.v1.ClassifyResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_classify_proto_init() }
func file_classify_proto_init() {
	if File_classify_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_classify_proto_rawDesc), len(file_classify_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_classify_proto_goTypes,
		DependencyIndexes: file_classify_proto_depIdxs,
		MessageInfos:      file_classify_proto_msgTypes,
	}.Build()
	File_classify_proto = out.File
	file_classify_proto_goTypes = nil
	file_classify_proto_depIdxs = nil
}
