// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.1
// source: convert.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConvertRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw document bytes (DOC, XLS, PPT).
	Document []byte `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	// MIME type of the input document.
	MimeType      string `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertRequest) Reset() {
	*x = ConvertRequest{}
	mi := &file_convert_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertRequest) ProtoMessage() {}

func (x *ConvertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_convert_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertRequest.ProtoReflect.Descriptor instead.
func (*ConvertRequest) Descriptor() ([]byte, []int) {
	return file_convert_proto_rawDescGZIP(), []int{0}
}

func (x *ConvertRequest) GetDocument() []byte {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *ConvertRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

type ConvertResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Converted document bytes (DOCX, XLSX, PPTX).
	Document []byte `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	// MIME type of the converted output.
	MimeType      string `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertResponse) Reset() {
	*x = ConvertResponse{}
	mi := &file_convert_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertResponse) ProtoMessage() {}

func (x *ConvertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_convert_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertResponse.ProtoReflect.Descriptor instead.
func (*ConvertResponse) Descriptor() ([]byte, []int) {
	return file_convert_proto_rawDescGZIP(), []int{1}
}

func (x *ConvertResponse) GetDocument() []byte {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *ConvertResponse) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

var File_convert_proto protoreflect.FileDescriptor

const file_convert_proto_rawDesc = "" +
	"\n" +
	"\rconvert.proto\x12\x10argus.convert.v1\"I\n" +
	"\x0eConvertRequest\x12\x1a\n" +
	"\bdocument\x18\x01 \x01(\fR\bdocument\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\"J\n" +
	"\x0fConvertResponse\x12\x1a\n" +
	"\bdocument\x18\x01 \x01(\fR\bdocument\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType2h\n" +
	"\x0eConvertService\x12V\n" +
	"\x0fConvertDocument\x12 .argus.convert.v1.ConvertRequest\x1a!.argus.convert.v1.ConvertResponseB'Z%github.com/zoobz-io/argus/proto;protob\x06proto3"

var (
	file_convert_proto_rawDescOnce sync.Once
	file_convert_proto_rawDescData []byte
)

func file_convert_proto_rawDescGZIP() []byte {
	file_convert_proto_rawDescOnce.Do(func() {
		file_convert_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_convert_proto_rawDesc), len(file_convert_proto_rawDesc)))
	})
	return file_convert_proto_rawDescData
}

var file_convert_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_convert_proto_goTypes = []any{
	(*ConvertRequest)(nil),  // 0: argus.convert.v1.ConvertRequest
	(*ConvertResponse)(nil), // 1: argus.convert.v1.ConvertResponse
}
var file_convert_proto_depIdxs = []int32{
	0, // 0: argus.convert.v1.ConvertService.ConvertDocument:input_type -> argus.convert.v1.ConvertRequest
	1, // 1: argus.convert.v1.ConvertService.ConvertDocument:output_type -> argus.convert.v1.ConvertResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_convert_proto_init() }
func file_convert_proto_init() {
	if File_convert_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_convert_proto_rawDesc), len(file_convert_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_convert_proto_goTypes,
		DependencyIndexes: file_convert_proto_depIdxs,
		MessageInfos:      file_convert_proto_msgTypes,
	}.Build()
	File_convert_proto = out.File
	file_convert_proto_goTypes = nil
	file_convert_proto_depIdxs = nil
}
