// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.1
// source: ocr.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExtractTextRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw document bytes.
	Document []byte `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	// MIME type of the document (e.g., "image/png", "application/pdf").
	MimeType string `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	// BCP-47 language hint (e.g., "eng"). Optional.
	Language      string `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractTextRequest) Reset() {
	*x = ExtractTextRequest{}
	mi := &file_ocr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractTextRequest) ProtoMessage() {}

func (x *ExtractTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ocr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractTextRequest.ProtoReflect.Descriptor instead.
func (*ExtractTextRequest) Descriptor() ([]byte, []int) {
	return file_ocr_proto_rawDescGZIP(), []int{0}
}

func (x *ExtractTextRequest) GetDocument() []byte {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *ExtractTextRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *ExtractTextRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type ExtractTextResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Extracted text content.
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// OCR confidence score (0.0 to 1.0).
	Confidence float32 `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	// Number of pages processed.
	Pages         int32 `protobuf:"varint,3,opt,name=pages,proto3" json:"pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractTextResponse) Reset() {
	*x = ExtractTextResponse{}
	mi := &file_ocr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractTextResponse) ProtoMessage() {}

func (x *ExtractTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ocr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractTextResponse.ProtoReflect.Descriptor instead.
func (*ExtractTextResponse) Descriptor() ([]byte, []int) {
	return file_ocr_proto_rawDescGZIP(), []int{1}
}

func (x *ExtractTextResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ExtractTextResponse) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *ExtractTextResponse) GetPages() int32 {
	if x != nil {
		return x.Pages
	}
	return 0
}

var File_ocr_proto protoreflect.FileDescriptor

const file_ocr_proto_rawDesc = "" +
	"\n" +
	"\tocr.proto\x12\fargus.ocr.v1\"i\n" +
	"\x12ExtractTextRequest\x12\x1a\n" +
	"\bdocument\x18\x01 \x01(\fR\bdocument\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\"_\n" +
	"\x13ExtractTextResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02R\n" +
	"confidence\x12\x14\n" +
	"\x05pages\x18\x03 \x01(\x05R\x05pages2`\n" +
	"\n" +
	"OCRService\x12R\n" +
	"\vExtractText\x12 .argus.ocr.v1.ExtractTextRequest\x1a!.argus.ocr.v1.ExtractTextResponseB'Z%github.com/zoobz-io/argus/proto;protob\x06proto3"

var (
	file_ocr_proto_rawDescOnce sync.Once
	file_ocr_proto_rawDescData []byte
)

func file_ocr_proto_rawDescGZIP() []byte {
	file_ocr_proto_rawDescOnce.Do(func() {
		file_ocr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ocr_proto_rawDesc), len(file_ocr_proto_rawDesc)))
	})
	return file_ocr_proto_rawDescData
}

var file_ocr_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ocr_proto_goTypes = []any{
	(*ExtractTextRequest)(nil),  // 0: argus.ocr.v1.ExtractTextRequest
	(*ExtractTextResponse)(nil), // 1: argus.ocr.v1.ExtractTextResponse
}
var file_ocr_proto_depIdxs = []int32{
	0, // 0: argus.ocr.v1.OCRService.ExtractText:input_type -> argus.ocr.v1.ExtractTextRequest
	1, // 1: argus.ocr.v1.OCRService.ExtractText:output_type -> argus.ocr.v1.ExtractTextResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ocr_proto_init() }
func file_ocr_proto_init() {
	if File_ocr_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ocr_proto_rawDesc), len(file_ocr_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ocr_proto_goTypes,
		DependencyIndexes: file_ocr_proto_depIdxs,
		MessageInfos:      file_ocr_proto_msgTypes,
	}.Build()
	File_ocr_proto = out.File
	file_ocr_proto_goTypes = nil
	file_ocr_proto_depIdxs = nil
}
